apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: photoapp
type: Opaque
stringData:
  MONGO_PASS: "change-me"
  JWT_SECRET: "change-me-to-random-string"
  DB_URL: "mongodb://root:change-me@mongo:27017/photoApp?authSource=admin"
